import { test } from "../BesttoFixture/MysaleszaFixture";
import * as crm from "../MysalezaJson/Login-test-data.json"
import * as unit from "../MysalezaJson/Products-test-data.json"
import * as role from "../MysalezaJson/MainModules-test-data.json"
import * as inventory from "../MysalezaJson/Inventory-test-data.json"
import * as presales from "../MysalezaJson/PerSales-test-data.json"
import * as sales from "../MysalezaJson/Sales-test-data.json"
import * as postsales from "../MysalezaJson/PostSales-test-data.json"
import * as taskmanagement from "../MysalezaJson/TaskManagement-test-data.json"



test("login_test_01", async ({ page, baseURL, login }) => {
    await page.goto(`${baseURL}login`)
    await login.loginscreen(crm.Username)
    await login.loginscreen1(crm.Password)
    await login.loginscreen2()
})
test("product_test_02", async ({ page, baseURL, login, products }) => { 
    await page.goto(`${baseURL}dashboard`)
    await login.logs(crm.Username, crm.Password)
    await products.clickaproduct()
    await products.clickaunits()
    await products.clickaaddbtn()
    await products.enteraunit(unit.unitname)
    await products.clickasubmit()
    await products.clickacategory()
    await products.clickaddcategory()
    await products.enteracategory(unit.category)
    await products.clickacategorysumbit()
    await products.clickaproduct()
    await products.clickaddproduct()
    await products.ProductOwnerName()
    await products.ProductName(unit.productname)
    await products.ProductCode(unit.productcode)
    await products.VendorName()
    await products.ProductStatus()
    await products.Category()
    await products.Manufacturer()
    await products.SalesStartDate(unit.salesstartdate)
    await products.SalesEndDate(unit.salesenddate)
    await products.SupportStartDate(unit.supportsartdate)
    await products.SupportEndDate(unit.supportenddate)
    await products.UnitPrice(unit.unitprice)
    await products.CommissionRate(unit.comRate)
    await products.Tax()
    await products.Units()
    await products.QtyOrdered(unit.qtyordered)
    await products.QtyInStock(unit.qtyinstock)
    await products.ReorderLevel(unit.recorder)
    await products.QtyInDemand(unit.qtyindemand)
    await products.Specification(unit.specification)
    await products.CreatedProduct()
})
test("mainmodule_test_03", async ({ page, baseURL, manageaccess, manageprivilege, roles, rolespermission, company, users,login }) => {
    await page.goto(`${baseURL}dashboard`)
    await login.logs(crm.Username,crm.Password)
    await manageaccess.ClickSuperAdmin()
    await manageaccess.ClickManageAccess()
    await manageaccess.AddAccess()
    await manageaccess.AccessName(role.accessname)
    await manageaccess.AccessSumbit()
    await manageprivilege.ClicPrivilege()
    await manageprivilege.ClickAddPrivilege()
    await manageprivilege.PrivilegeName(role.privilegename)
    await manageprivilege.DropDownAccess()
    await manageprivilege.PrivilegeSubmit()
    await roles.ClickRoles()
    await roles.ClickAddRoles()
    await roles.RoleName(role.rolename)
    await roles.ChoosePrivilege()
    await roles.RoleSumbit()
    await rolespermission.Clickrolespermission()
    await rolespermission.ClickaddRoles()
    await rolespermission.RoleName(role.rolenames)
    await rolespermission.RoleSumbit()
    await company.ClickCompany()
    await company.CompanyName(role.companyname)
    await company.EmailAddress(role.email)
    await company.Website(role.website)
    await company.Password(role.companyPassword)
    await company.ConfirmPassword(role.companyPassword)
    await company.GstNo(role.gstno)
    await company.ContactNo(role.contactno)
    await company.MoblieNo(role.moblieno)
    await company.City(role.city)
    await company.State(role.states)
    await company.Address(role.addresscm)
    await company.CompanySumbit()
    await users.ClickUser()
    await users.ClickAddUser()
    await users.FristName(role.fristname)
    await users.LastName(role.lastname)
    await users.Email(role.email)
    await users.PhoneNumber(role.phonenumber)
    await users.Role()
    await users.Password(role.userpassword)
    await users.ConfrimPassword(role.userpassword)
    await users.Address(role.address)
    await users.State(role.state)
    await users.Country(role.country)
    await users.Status()
    await users.UserSumbit()
})
test("inventory_test_04",async({ page,baseURL,login,vendors,purchaseorders,pricebook}) =>{
    await page.goto(`${baseURL}dashboard`)
    await login.logs(crm.Username,crm.Password)
    await vendors.ClickVendors()
    await vendors.AddVendors()
    await vendors.VendorOwnerName()
    await vendors.VendorName(inventory.vendorname)
    await vendors.Emailid(inventory.emailid)
    await vendors.Website(inventory.website)
    await vendors.PhoneNumber(inventory.pnumber)
    await vendors.CategoryName()
    await vendors.EmailOptOut()
    await vendors.Street(inventory.street)
    await vendors.City(inventory.city)
    await vendors.State(inventory.state)
    await vendors.Country(inventory.country)
    await vendors.Zipcode(inventory.zipcode)
    await vendors.Description(inventory.vendordescription)
    await vendors.CreatedVendorSumbit()
    await purchaseorders.ClickPurchaseOrder()
    await purchaseorders.ClickaddPurchaseorder()
    await purchaseorders.ClickPurchaseOrder()
    await purchaseorders.Subject(inventory.subject)
    await purchaseorders.SupplierName()
    await purchaseorders.RequisitionNumber(inventory.requisitionnumber)
    await purchaseorders.TrackingNumber(inventory.trackingnumber)
    await purchaseorders.MoblieNumber(inventory.moblienumber)
    await purchaseorders.DueDate(inventory.duedate)
    await purchaseorders.Carrier()
    await purchaseorders.Tax()
    await purchaseorders.SalesCommission(inventory.salescommission)
    await purchaseorders.Status()
    await purchaseorders.Street(inventory.purchasestreet)
    await purchaseorders.City(inventory.purchasecity)
    await purchaseorders.State(inventory.purchasestate)
    await purchaseorders.Country(inventory.purchasecountry)
    await purchaseorders.Pincode(inventory.purchasepincode)
    await purchaseorders.ClickCopyAddress()
    await purchaseorders.ClickAProductInPurchase()
    await purchaseorders.ClickAddProduct(inventory.quantity)
    await purchaseorders.ClickDiscount(inventory.discount)
    await purchaseorders.TermsandConditions(inventory.termsandconditions)
    await purchaseorders.Description(inventory.purdescription)
    await purchaseorders.CreatedPurchaseorderSumbit()
    await pricebook.ClickaPricebook()
    await pricebook.ClickaddPricebook()
    await pricebook.PriceBookOwner()
    await pricebook.PriceBookName(inventory.pricebookname)
    await pricebook.PBProduct()
    await pricebook.PBStatus()
    await pricebook.ListPrice(inventory.listprice)
    await pricebook.PricingModel()  
    await pricebook.Description(inventory.description)
    await pricebook.CreatedPriceBookSumbit()


})
test("presales_test_05",async({ page,baseURL,login,campaign,leadscompany,leadsindividual,account,contact,opportunitycompany,opportunityindividual})=>{
    await page.goto(`${baseURL}dashboard`)
    await login.logs(crm.Username,crm.Password)
    await campaign.ClickCampaign()
    await campaign.ClickAddCampaign()
    await campaign.CampaignOwner()
    await campaign.CampaignName(presales.campaignname)
    await campaign.CampaignMode()
    await campaign.CampaignStatus()
    await campaign.NumberofEmployees(presales.noemployee)
    await campaign.CampaignStartDate(presales.campaignsdate)
    await campaign.CampaignEndDate(presales.campaignedate)
    await campaign.ExpectedRevenue(presales.expectedrevenue)
    await campaign.BudgetedCost(presales.budgetedcost)
    await campaign.ActualCost(presales.actualcost)
    await campaign.ExpectedResponse(presales.expectedresponse)
    await campaign.CampaignDescription(presales.campaigndescription)
    await campaign.CampaignSubmit()
    await leadscompany.ClickLead()
    await leadscompany.ClickAddLead()
    await leadscompany.LeadType()
    await leadscompany.AssignEmployee()
    await leadscompany.LeadStatus()
    await leadscompany.LeadSource()
    await leadscompany.EmailAddress(presales.companyemail)
    await leadscompany.MobileNumber(presales.companymobilenumber)
    await leadscompany.Street(presales.companystreet)
    await leadscompany.City(presales.companycity)
    await leadscompany.State(presales.companystate)
    await leadscompany.Country(presales.companycountry)
    await leadscompany.PostalCode(presales.companypostalcode)
    await leadscompany.CompanyName(presales.leadcompanyname)
    await leadscompany.Website(presales.leadwebsite)
    await leadscompany.Industry()
    await leadscompany.Designation(presales.leaddesignation)
    await leadscompany.LeadName(presales.leadnamecompany)
    await leadscompany.Rating()
    await leadscompany.EmployeeCount(presales.employeecount)
    await leadscompany.Description(presales.leaddescription)
    await leadscompany.leadcompanySubmit()
    await leadsindividual.ClickLead()
    await leadsindividual.ClickAddLead()
    await leadsindividual.LeadType()
    await leadsindividual.AssignEmployee()
    await leadsindividual.LeadStatus()
    await leadsindividual.LeadSource()
    await leadsindividual.Salutation()
    await leadsindividual.Fristname(presales.individualfristname)
    await leadsindividual.Lastname(presales.individuallastname)
    await leadsindividual.Designation(presales.individualdesignation)
    await leadsindividual.EmailAddress(presales.individualemail)
    await leadsindividual.MobileNumber(presales.individualmobilenumber)
    await leadsindividual.Street(presales.individualstreet)
    await leadsindividual.City(presales.individualcity)
    await leadsindividual.State(presales.individualstate)
    await leadsindividual.Country(presales.individualcountry)
    await leadsindividual.PostalCode(presales.individualpostalcode)
    await leadsindividual.Description(presales.individualdescription)
    await leadsindividual.IndividualSubmit()
    await account.ClickAccount()
    await account.ClickAddAccount()
    await account.AccountOwner()
    await account.AccountName(presales.accountname)
    await account.PhoneNumber(presales.accountphonenumber)
    await account.AccountNo(presales.accountno)
    await account.AccountType()
    await account.Ownership()
    await account.Industry()
    await account.NoOfEmployee(presales.noofemployee)
    await account.AnnualRevenue(presales.annualrevenuse)
    await account.SICCode(presales.siccode)
    await account.BillingStreet(presales.billingstreet)
    await account.BillingCity(presales.billingcity)
    await account.BillingState(presales.billingstate)
    await account.BillingCountry(presales.billingcountry)
    await account.BillingCode(presales.billingcode)
    await account.ClickAccountCopyAddress()
    await account.AccountDescription(presales.accountdescription)
    await account.AccountSubmit()
    await contact.ClickContacts()
    await contact.ClickAddContacts()
    await contact.Salutation()
    await contact.Fristname(presales.contactsfristname)
    await contact.Lastname(presales.contactslastname)
    await contact.AccountName()
    await contact.Department(presales.department)
    await contact.Email(presales.contactsemail)
    await contact.phoneNumber(presales.contactsphonenumber)
    await contact.LeadSource()
    await contact.ContactOwner()
    await contact.DateOfBirth(presales.dateofbirth)
    await contact.Title(presales.title)
    await contact.AssistantName(presales.assistantname)
    await contact.AssistantNumber(presales.assistantnumber)
    await contact.MobileNumber(presales.contactsmobilenumber)
    await contact.HomePhoneNumber(presales.homephonenumber)
    await contact.BillingStreet(presales.contactsbillingstreet)
    await contact.BillingCity(presales.contactsbillingcity)
    await contact.BillingState(presales.contactsbillingstate)
    await contact.BillingCountry(presales.contactsbillingcountry)
    await contact.BillingPostalCode(presales.contactsbillingpostalcode)
    await contact.ClickContactsCopyAddress()
    await contact.ContactsDescription(presales.contactdescription)
    await contact.ContactSubmit()
    await opportunitycompany.ClickOpportunity()
    await opportunitycompany.ClickAddOpportunity()
    await opportunitycompany.OpportunityType()
    await opportunitycompany.DealOwner()
    await opportunitycompany.DealName(presales.dealname)
    await opportunitycompany.WebSite(presales.website)
    await opportunitycompany.Industry()
    await opportunitycompany.AccountName()
    await opportunitycompany.ExpectedCloseDate(presales.companyexpectedclosedate)
    await opportunitycompany.Amount(presales.amount)
    await opportunitycompany.SalesStage()
    await opportunitycompany.ExpectedRevenue(presales.oppexpectedrevenue)
    await opportunitycompany.NextStep(presales.nextstep)
    await opportunitycompany.LeadSource()
    await opportunitycompany.CampaignSource()
    await opportunitycompany.OpportunityCompanyDescription(presales.opportunitycompanydescription)
    await opportunitycompany.OpportunityCompanySubmit()
    





   

    
})
test("sales_test_06",async({ page,baseURL,login,invoice,quotation,salesorder})=>{
    await page.goto(`${baseURL}dashboard`)
    await login.logs(crm.Username,crm.Password)
    await invoice.ClickInvoice()
    await invoice.ClickAddInvoice()
    await invoice.OrderNo()
    await invoice.InvoiceOwner()
    await invoice.PurchaseOrder(sales.PurchaseOrder)
    await invoice.SalesCommision(sales.SalesCommision)
    await invoice.Status()
    await invoice.AccountName(sales.accountname)
    await invoice.ContactName(sales.contactname)
    await invoice.DealName(sales.dealname)
    await invoice.Subject(sales.subject)
    await invoice.DueDate(sales.duedate)
    await invoice.InvoiceStreet(sales.invoicestreet)
    await invoice.InvoiceCity(sales.invoicecity)
    await invoice.InvoiceState(sales.invoicestate)
    await invoice.InvoicePincode(sales.invoicepincode)
    await invoice.InvoiceCountry(sales.invoicecountry)
    await invoice.InvoiceClickCopyAddress()
    await invoice.ClickAProductInInvoice()
    await invoice.ClickAProductInInvoice()
    await invoice.InvoiceClickAddProduct(sales.invoicequantity)
    await invoice.InvoiceClickDiscount(sales.invoicediscount)
    await invoice.InvoiceTermsandConditions(sales.invoicetermsandconditions)
    await invoice.InvoiceDescription(sales.invoicedescription)
    await invoice.CreatedInvoiceSumbit()
    await quotation.ClickQuotations()
    await quotation.ClickAddQuotations()
    await quotation.QuoteOwner()
    await quotation.Subject(sales.quosubject)
    await quotation.ContactName()
    await quotation.DealName()
    await quotation.AccountName()
    await quotation.DueDate(sales.quosubject)
    await quotation.QuotesStage()
    await quotation.Carrier()
    await quotation.QuotationsStreet(sales.quotationsstreet)
    await quotation.QuotationsCity(sales.quotationscity)
    await quotation.QuotationsState(sales.quotationsstate)
    await quotation.QuotationsCountry(sales.quotationscountry)
    await quotation.QuotationsPincode(sales.quotationspincode)
    await quotation.QuotationsClickCopyAddress()
    await quotation.ClickAProductInQuotations()
    await quotation.QuotationsClickAddProduct(sales.quotationsquantity)
    await quotation.QuotationsClickDiscount(sales.quotationsdiscount)
    await quotation.QuotationsTermsandConditions(sales.quotationstermsandconditions)
    await quotation.QuotationsDescription(sales.quotationsdescription)
    await quotation.CreatedQuotationsSumbit()
    await salesorder.ClickSalesorder()
    await salesorder.ClickAddSalesorder()
    await salesorder.SalesOrderOwner()
    await salesorder.DealName()
    await salesorder.Subject(sales.salessubject)
    await salesorder.PurchaseOrderNo(sales.purchaseorderno)
    await salesorder.Status()
    await salesorder.CustomerNo(sales.customerno)
    await salesorder.DueDate(sales.salesduedate)
    await salesorder.ContactName()
    await salesorder.Pending(sales.pending)
    await salesorder.Tax()
    await salesorder.Carrier()
    await salesorder.SalesCommision(sales.SOSalesCommision)
    await salesorder.AccountName()
    await salesorder.SalesorderStreet(sales.salesorderstreet)
    await salesorder.SalesorderCity(sales.salesordercity)
    await salesorder.SalesorderState(sales.salesorderstate)
    await salesorder.SalesorderCountry(sales.salesordercountry)
    await salesorder.SalesorderPincode(sales.salesorderpincode)
    await salesorder.SalesorderClickCopyAddress()
    await salesorder.ClickAProductInSalesorder()
    await salesorder.SalesorderClickAddProduct(sales.salesorderquantity)
    await salesorder.SalesorderClickDiscount(sales.salesorderdiscount)
    await salesorder.SalesorderTermsandConditions(sales.salesordertermsandconditions)
    await salesorder.SalesorderDescription(sales.salesorderdescription)
    await salesorder.CreatedSalesorderSumbit()

    

})
test("postsales_test_07", async ({ page, baseURL, login,invoicecheck,createcase,solution }) => {
    await page.goto(`${baseURL}dashboard`)
    await login.logs(crm.Username, crm.Password)
    await invoicecheck.ClickInvoiceCheck()
    await invoicecheck.InvoiceNumber(postsales.invoicenumber)
    await invoicecheck.SearchInvoice()
    await invoicecheck.CreatedCase()
    await invoicecheck.CaseOwner()
    await invoicecheck.Status()
    await invoicecheck.Type()
    await invoicecheck.Priority()
    await invoicecheck.CaseOrigin()
    await invoicecheck.CaseReason()
    await invoicecheck.Contact()
    await invoicecheck.Subject(postsales.subject)
    await invoicecheck.Account()
    await invoicecheck.CreateCaseInInvoiceCheck()
    await createcase.ClickCase()
    await createcase.ClickAddCase()
    await createcase.CaseInvoiceNumber(postsales.caseinvoicenumber)
    await createcase.SearchInvoice()
    await createcase.CCaseOwner()
    await createcase.CaseStatus()
    await createcase.CaseType()
    await createcase.CasePriority()
    await createcase.CCaseOrigin()
    await createcase.CCaseReason()
    await createcase.CaseContact()
    await createcase.CaseSubject(postsales.casesubject)
    await createcase.CaseAccount()
    await createcase.CaseRelatedTo(postsales.caserelatedto)
    await createcase.CaseOpportunity()
    await createcase.CaseEmail(postsales.caseemail)
    await createcase.CaseContactNumber(postsales.casecontactnumber)
    await createcase.CaseDescription(postsales.casedescription)
    await createcase.CaseInternalComments(postsales.caseinternalcomments)
    await createcase.CaseSolutions(postsales.casesolutions)
    await createcase.CreateCase()
    await solution.clickOnSolution()
    await solution.clickOnAddSolution()
    await solution.SolutionOwner()
    await solution.SolutionTitle(postsales.Solutiontitle)
    await solution.Status()
    await solution.ProductName()
    await solution.Question(postsales.question)
    await solution.Answer(postsales.answer)
    await solution.Description(postsales.solutiondescription)
    await solution.clickOnSave()

    
})
test("taskmanagement_test_08", async ({ page, baseURL, login,task,workitem,sla,skills,workitemskills,entitymanagement,workitemsla }) => {
    await page.goto(`${baseURL}dashboard`)
    await login.logs(crm.Username, crm.Password)
    await task.clickOnTask()
    await task.clickOnAddTask()
    await task.EmployeeName()
    await task.LeadName()
    await task.RelatedTo()
    await task.WorkItemName()
    await task.Priority()
    await task.Status()
    await task.DueDate(taskmanagement.duedate)
    await task.Description(taskmanagement.taskdescription)
    await task.clickOnSave()
    await workitem.clickOnWorkItem()
    await workitem.clickOnAddWorkItem()
    await workitem.WorkItemType(taskmanagement.workitemtype)
    await workitem.WorkItemCode(taskmanagement.workItemcode)
    await workitem.WorkItemName(taskmanagement.workItemname)
    await workitem.ClickOnSave()
    await sla.clickOnSla()
    await sla.clickOnAddSla()
    await sla.SLANoofDays(taskmanagement.slanoofdays)
    await sla.SLACode(taskmanagement.slacode)
    await sla.SLADate(taskmanagement.sladate)
    await sla.SLADescription(taskmanagement.sladescription)
    await sla.clickOnSave()
    await skills.clickOnSkills()
    await skills.clickOnAddSkills()
    await skills.SkillsName(taskmanagement.skillsname)
    await skills.SkillsName(taskmanagement.skillsname)
    await skills.clickOnSave()
    await workitemskills.clickOnWorkItemSkills()
    await workitemskills.clickOnAddWorkItemSkills()
    await workitemskills.SkillsName()
    await workitemskills.WorkItemName()
    await workitemskills.clickOnSave()
    await entitymanagement.clickOnEntityManagement()
    await entitymanagement.clickOnAddEntityManagement()
    await entitymanagement.EntityName()
    await entitymanagement.WorkItemName()
    await entitymanagement.clickOnSave()
    await workitemsla.clickOnWorkItemSLA()
    await workitemsla.clickOnAddWorkItemSLA()
    await workitemsla.WorkItemName()
    await workitemsla.SLADays()
    await workitemsla.clickOnSave()


    

    
})