import { test } from "../BesttoFixture/MysaleszaFixture";
import * as crm from "../MysalezaJson/Login-test-data.json"
import * as unit from "../MysalezaJson/Products-test-data.json"
import * as role from "../MysalezaJson/MainModules-test-data.json"
import * as inventory from "../MysalezaJson/Inventory-test-data.json"
import * as presales from "../MysalezaJson/PreSales-test-data.json"



test("login_test_01", async ({ page, baseURL, login }) => {
    await page.goto(`${baseURL}login`)
    await login.loginscreen(crm.Username)
    await login.loginscreen1(crm.Password)
    await login.loginscreen2()
})
test("product_test_02", async ({ page, baseURL, login, products }) => { 
    await page.goto(`${baseURL}dashboard`)
    await login.logs(crm.Username, crm.Password)
    await products.clickaproduct()
    await products.clickaunits()
    await products.clickaaddbtn()
    await products.enteraunit(unit.unitname)
    await products.clickasubmit()
    await products.clickacategory()
    await products.clickaddcategory()
    await products.enteracategory(unit.category)
    await products.clickacategorysumbit()
    await products.clickaproduct()
    await products.clickaddproduct()
    await products.ProductOwnerName()
    await products.ProductName(unit.productname)
    await products.ProductCode(unit.productcode)
    await products.VendorName()
    await products.ProductStatus()
    await products.Category()
    await products.Manufacturer()
    await products.SalesStartDate(unit.salesstartdate)
    await products.SalesEndDate(unit.salesenddate)
    await products.SupportStartDate(unit.supportsartdate)
    await products.SupportEndDate(unit.supportenddate)
    await products.UnitPrice(unit.unitprice)
    await products.CommissionRate(unit.comRate)
    await products.Tax()
    await products.Units()
    await products.QtyOrdered(unit.qtyordered)
    await products.QtyInStock(unit.qtyinstock)
    await products.ReorderLevel(unit.recorder)
    await products.QtyInDemand(unit.qtyindemand)
    await products.Specification(unit.specification)
    await products.CreatedProduct()
})
test("mainmodule_test_03", async ({ page, baseURL, manageaccess, manageprivilege, roles, rolespermission, company, users,login }) => {
    await page.goto(`${baseURL}dashboard`)
    await login.logs(crm.Username,crm.Password)
    await manageaccess.ClickSuperAdmin()
    await manageaccess.ClickManageAccess()
    await manageaccess.AddAccess()
    await manageaccess.AccessName(role.accessname)
    await manageaccess.AccessSumbit()
    await manageprivilege.ClicPrivilege()
    await manageprivilege.ClickAddPrivilege()
    await manageprivilege.PrivilegeName(role.privilegename)
    await manageprivilege.DropDownAccess()
    await manageprivilege.PrivilegeSubmit()
    await roles.ClickRoles()
    await roles.ClickAddRoles()
    await roles.RoleName(role.rolename)
    await roles.ChoosePrivilege()
    await roles.RoleSumbit()
    await rolespermission.Clickrolespermission()
    await rolespermission.ClickaddRoles()
    await rolespermission.RoleName(role.rolenames)
    await rolespermission.RoleSumbit()
    await company.ClickCompany()
    await company.ClickAddCompany()
    await company.CompanyName(role.companyname)
    await company.EmailAddress(role.email)
    await company.Website(role.website)
    await company.Password(role.companyPassword)
    await company.ConfirmPassword(role.companyPassword)
    await company.GstNo(role.gstno)
    await company.ContactNo(role.contactno)
    await company.MoblieNo(role.moblieno)
    await company.City(role.city)
    await company.State(role.states)
    await company.Address(role.addresscm)
    await company.CompanySumbit()
    await users.ClickUser()
    await users.ClickAddUser()
    await users.FristName(role.fristname)
    await users.LastName(role.lastname)
    await users.Email(role.email)
    await users.PhoneNumber(role.phonenumber)
    await users.Role()
    await users.Password(role.userpassword)
    await users.ConfrimPassword(role.userpassword)
    await users.Address(role.address)
    await users.State(role.state)
    await users.Country(role.country)
    await users.Status()
    await users.UserSumbit()
})
test("inventory_test_04",async({ page,baseURL,login,vendors,purchaseorders,pricebook}) =>{
    await page.goto(`${baseURL}dashboard`)
    await login.logs(crm.Username,crm.Password)
    await vendors.ClickVendors()
    await vendors.AddVendors()
    await vendors.VendorOwnerName()
    await vendors.VendorName(inventory.vendorname)
    await vendors.Emailid(inventory.emailid)
    await vendors.Website(inventory.website)
    await vendors.PhoneNumber(inventory.pnumber)
    await vendors.CategoryName()
    await vendors.EmailOptOut()
    await vendors.Street(inventory.street)
    await vendors.City(inventory.city)
    await vendors.State(inventory.state)
    await vendors.Country(inventory.country)
    await vendors.Zipcode(inventory.zipcode)
    await vendors.Description(inventory.vendordescription)
    await vendors.CreatedVendorSumbit()
    await purchaseorders.ClickPurchaseOrder()
    await purchaseorders.ClickaddPurchaseorder()
    await purchaseorders.ClickPurchaseOrder()
    await purchaseorders.Subject(inventory.subject)
    await purchaseorders.SupplierName()
    await purchaseorders.RequisitionNumber(inventory.requisitionnumber)
    await purchaseorders.TrackingNumber(inventory.trackingnumber)
    await purchaseorders.MoblieNumber(inventory.moblienumber)
    await purchaseorders.DueDate(inventory.duedate)
    await purchaseorders.Carrier()
    await purchaseorders.Tax()
    await purchaseorders.SalesCommission(inventory.salescommission)
    await purchaseorders.Status()
    await purchaseorders.Street(inventory.purchasestreet)
    await purchaseorders.City(inventory.purchasecity)
    await purchaseorders.State(inventory.purchasestate)
    await purchaseorders.Country(inventory.purchasecountry)
    await purchaseorders.Pincode(inventory.purchasepincode)
    await purchaseorders.ClickCopyAddress()
    await purchaseorders.ClickAProductInPurchase()
    await purchaseorders.ClickAddProduct(inventory.quantity)
    await purchaseorders.ClickDiscount(inventory.discount)
    await purchaseorders.TermsandConditions(inventory.termsandconditions)
    await purchaseorders.Description(inventory.purdescription)
    await purchaseorders.CreatedPurchaseorderSumbit()
    await pricebook.ClickaPricebook()
    await pricebook.ClickaddPricebook()
    await pricebook.PriceBookOwner()
    await pricebook.PriceBookName(inventory.pricebookname)
    await pricebook.PBProduct()
    await pricebook.PBStatus()
    await pricebook.ListPrice(inventory.listprice)
    await pricebook.PricingModel()  
    await pricebook.Description(inventory.description)
    await pricebook.CreatedPriceBookSumbit()


})
test("presales_test_05",async({ page,baseURL,login,campaign,leadscompany,leadsindividual,account,contact,opportunitycompany,opportunityindividual})=>{
    await page.goto(`${baseURL}dashboard`)
    await login.logs(crm.Username,crm.Password)
    await campaign.ClickCampaign()
    await campaign.ClickAddCampaign()
    await campaign.CampaignOwner()
    await campaign.CampaignName(presales.campaignname)
    await campaign.c()
})